"""initial schema

Revision ID: ed9869fdf610
Revises: 
Create Date: 2026-08-01 13:52:58.614206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed9869fdf610'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_weeks',
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('first_kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('all_final', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('season', 'week')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('leagues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sleeper_league_id', sa.String(length=64), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('total_rosters', sa.Integer(), nullable=False),
    sa.Column('loser_rule', sa.String(length=32), nullable=False),
    sa.Column('lock_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('discord_webhook_url', sa.Text(), nullable=True),
    sa.Column('first_scored_week', sa.Integer(), nullable=False),
    sa.Column('last_scored_week', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sleeper_league_id', 'season', name='uq_league_season')
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leagues_sleeper_league_id'), ['sleeper_league_id'], unique=False)

    op.create_table('sleeper_links',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sleeper_user_id', sa.String(length=64), nullable=False),
    sa.Column('sleeper_username', sa.String(length=255), nullable=False),
    sa.Column('sleeper_display_name', sa.String(length=255), nullable=True),
    sa.Column('sleeper_avatar', sa.String(length=255), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('sleeper_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleeper_links_sleeper_user_id'), ['sleeper_user_id'], unique=True)

    op.create_table('league_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('sleeper_user_id', sa.String(length=64), nullable=True),
    sa.Column('sleeper_roster_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'sleeper_roster_id', name='uq_member_roster'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_member_user')
    )
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_members_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_members_sleeper_user_id'), ['sleeper_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_members_user_id'), ['user_id'], unique=False)

    op.create_table('week_scores',
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('sleeper_roster_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'season', 'week', 'sleeper_roster_id')
    )
    op.create_table('parlay_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('scored_week', sa.Integer(), nullable=False),
    sa.Column('bet_week', sa.Integer(), nullable=False),
    sa.Column('loser_member_id', sa.Uuid(), nullable=True),
    sa.Column('loser_points', sa.Float(), nullable=True),
    sa.Column('tie_roster_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locks_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('final_odds', sa.String(length=32), nullable=True),
    sa.Column('stake_cents', sa.Integer(), nullable=True),
    sa.Column('payout_cents', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loser_member_id'], ['league_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', 'bet_week', name='uq_round_bet_week')
    )
    with op.batch_alter_table('parlay_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parlay_rounds_league_id'), ['league_id'], unique=False)
        batch_op.create_index('ix_round_league_season', ['league_id', 'season'], unique=False)

    op.create_table('legs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('espn_event_id', sa.String(length=32), nullable=True),
    sa.Column('american_odds', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['league_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['parlay_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'member_id', name='uq_leg_round_member')
    )
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legs_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legs_round_id'), ['round_id'], unique=False)

    op.create_table('notifications_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=320), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['parlay_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'kind', 'channel', 'target', name='uq_notification_once')
    )
    with op.batch_alter_table('notifications_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_log_round_id'), ['round_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_log_round_id'))

    op.drop_table('notifications_log')
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legs_round_id'))
        batch_op.drop_index(batch_op.f('ix_legs_member_id'))

    op.drop_table('legs')
    with op.batch_alter_table('parlay_rounds', schema=None) as batch_op:
        batch_op.drop_index('ix_round_league_season')
        batch_op.drop_index(batch_op.f('ix_parlay_rounds_league_id'))

    op.drop_table('parlay_rounds')
    op.drop_table('week_scores')
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_league_members_sleeper_user_id'))
        batch_op.drop_index(batch_op.f('ix_league_members_league_id'))

    op.drop_table('league_members')
    with op.batch_alter_table('sleeper_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleeper_links_sleeper_user_id'))

    op.drop_table('sleeper_links')
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_sleeper_league_id'))

    op.drop_table('leagues')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('nfl_weeks')
    # ### end Alembic commands ###
